site_name: WarpSTR documentation

theme:
  name: material
  palette:
    - scheme: default
      primary: amber
      toggle:
        icon: material/weather-night
        name: Switch to dark mode
    - scheme: slate
      primary: amber
      toggle:
        icon: material/weather-sunny
        name: Switch to light mode
  features:
    - navigation.instant
    - navigation.top  # back to top button
    - search.highlight

repo_name: 'fmfi-compbio/warpstr'
repo_url: 'https://github.com/fmfi-compbio/warpstr/'

nav:
  - Home: index.md
  - Install: installation.md
  - Running:
    - Overview: running_overview.md
    - Config: config.md
    - Advanced parameters: advanced_params.md
  - Output: output.md

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - toc:
      permalink: True
  - admonition
  - pymdownx.details
  - attr_list
  - md_in_html
