repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.3.0
    hooks:
      - id: double-quote-string-fixer
      - id: end-of-file-fixer
      - id: check-added-large-files
      - id: check-docstring-first
      - id: check-merge-conflict
-   repo: https://github.com/pycqa/flake8
    rev: '5.0.4'
    hooks:
    -   id: flake8
        args:
        - "--max-line-length=119"
-   repo: https://github.com/pre-commit/mirrors-isort
    rev: v5.10.1
    hooks:
    -   id: isort
        args:
        - "--line-length=119"
-   repo: https://github.com/pre-commit/mirrors-autopep8
    rev: 'v1.7.0'
    hooks:
    -   id: autopep8
        args: ["-i", "--max-line-length", "119"]
