name: warpstr_env
channels:
  - bioconda
  - conda-forge
  - defaults
dependencies:
  - python=3.7.9
  - ipython
  - numpy=1.20
  - biopython=1.75
  - h5py=3.4.0
  - hdf5=1.12.1
  - matplotlib=3.3.4
  - matplotlib-base=3.3.4
  - multiprocess=0.70.12.2
  - pandas=1.2.5
  - pip=21.2.4
  - pysam=0.16.0.1
  - pyyaml=5.4.1
  - scikit-learn=1.0.1
  - scipy=1.6.3
  - seaborn=0.11.1
